I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/combat.rpy", line 2, in script
    python:
  File "game/combat.rpy", line 56, in <module>
    combat_loop()
  File "game/combat.rpy", line 24, in combat_loop
    active_character.pick_move_player()
  File "game/initialize.rpy", line 55, in pick_move_player
    tempString += i.name + " "
AttributeError: 'str' object has no attribute 'name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/combat.rpy", line 2, in script
    python:
  File "D:\Fragmented-main\Fragmented-main\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Fragmented-main\Fragmented-main\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/combat.rpy", line 56, in <module>
    combat_loop()
  File "game/combat.rpy", line 24, in combat_loop
    active_character.pick_move_player()
  File "game/initialize.rpy", line 55, in pick_move_player
    tempString += i.name + " "
AttributeError: 'str' object has no attribute 'name'

Windows-10-10.0.19044 AMD64
Ren'Py 8.1.3.23091805
Fragmented 1.0
Sun Oct 29 19:16:48 2023
