I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script2.rpy", line 9, in script call
    "You decide it's time to part ways with Illyria and head towards the castle that looms in the distance. The path is treacherous, and the snow grows deeper with every step."
  File "game/equipment.rpy", line 5, in script
    python:
  File "game/equipment.rpy", line 22, in <module>
    if item not in equipment:
TypeError: argument of type 'Equipment' is not iterable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script2.rpy", line 9, in script call
    "You decide it's time to part ways with Illyria and head towards the castle that looms in the distance. The path is treacherous, and the snow grows deeper with every step."
  File "game/equipment.rpy", line 5, in script
    python:
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Git-Huh\Fragmented\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/equipment.rpy", line 22, in <module>
    if item not in equipment:
TypeError: argument of type 'Equipment' is not iterable

Windows-10-10.0.22635 AMD64
Ren'Py 8.1.3.23091805
Fragmented 1.0
Tue Dec  5 12:34:15 2023
